[book]
authors = ["Hugo Dutka"]
language = "en"
multilingual = false
src = "src"
title = "Hocus"

[output.html]
default-theme = "coal"
cname = "hocus.dev"
git-repository-url = "https://github.com/hocus-dev/docs"
